wip: work in progress
Signed-off-by: Mark S <the@wondersmith.dev>

diff --git a/.github/workflows/build-images.yaml b/.github/workflows/build-images.yaml
--- a/.github/workflows/build-images.yaml
+++ b/.github/workflows/build-images.yaml
@@ -1,17 +1,61 @@
+---
 name: Build Docker Images (Reusable)
 
 on:
   workflow_call:
     inputs:
       ref:
-        description: 'Git ref to checkout'
-        required: false
         type: string
+        required: false
         default: ${{ github.ref }}
+        description: Git ref to checkout
+      debug:
+        type: boolean
+        required: false
+        default: false
+        description: |
+          Enable upterm debugging
+
+          NOTE: only available when running locally with netkos/act
+      components:
+        type: string
+        required: false
+        description: |-
+          The list of components to build images for, formatted as a space-separated list of strings.
+
+          Defaults to: apiext emissary kat-client kat-server test-auth test-shadow test-stats
+        default: >-
+          apiext
+          emissary
+          kat-client
+          kat-server
+          test-auth
+          test-shadow
+          test-stats
+      artifact-bundle-prefix:
+        type: string
+        required: true
+        description: Prefix for arch-specific artifact bundle name
+
     outputs:
-      artifact-name-prefix:
-        description: 'Prefix for artifact names'
-        value: ${{ jobs.build-images.outputs.artifact-name-prefix }}
+      components:
+        value: ${{ jobs.build-images.outputs.components }}
+        description: >-
+          The list of components images were built for, formatted as a space-separated list of strings.
+      artifact-id:
+        value: ${{ jobs.build-images.outputs.artifact-id }}
+        description: GitHub ID of the built image artifact(s)
+      artifact-url:
+        value: ${{ jobs.build-images.outputs.artifact-url }}
+        description: >-
+          URL to download the built images artifact. Can be used in many scenarios
+          such as linking to images built by a specific CI run in issues or pull requests.
+          Users must be logged-in in order for this URL to work. This URL is valid as
+          long as the images artifact has not expired or the images artifact, run
+          or repository have not been deleted.
+      artifact-digest:
+        value: ${{ jobs.build-images.outputs.artifact-digest }}
+        description: SHA-256 digest of the built images artifact
 
 permissions:
   contents: read
@@ -23,7 +67,9 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        arch: [amd64, arm64]
+        arch:
+          - amd64
+          - arm64
         include:
           - arch: amd64
             runner: ubuntu-24.04
@@ -31,11 +77,14 @@ jobs:
             runner: ubuntu-24.04-arm
 
     outputs:
-      artifact-name-prefix: ${{ steps.set-outputs.outputs.artifact-name-prefix }}
+      components: ${{ inputs.components }}
+      artifact-id: ${{ steps.upload-image-tarballs.outputs.artifact-id }}
+      artifact-url: ${{ steps.upload-image-tarballs.outputs.artifact-url }}
+      artifact-digest: ${{ steps.upload-image-tarballs.outputs.artifact-digest }}
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           ref: ${{ inputs.ref }}
           fetch-depth: 0
@@ -54,11 +103,11 @@ jobs:
           distribution: goreleaser
 
       - name: Generate GoReleaser Config
-        run: |
-          python make-gorel.py \
-              --header gorel.prologue \
-              --arch ${{ matrix.arch }} \
-            > .goreleaser.yaml
+        run: >-
+          uv run -- python make-gorel.py
+          --header gorel.prologue
+          --arch ${{ matrix.arch }}
+          > .goreleaser.yaml
 
       - name: GoReleaser Check(s)
         shell: bash
@@ -66,35 +115,107 @@ jobs:
           goreleaser check
           goreleaser healthcheck
 
-      - name: GoReleaser Build
+      - id: goreleaser-build
+        name: GoReleaser Build
+        continue-on-error: ${{ env.ACT && inputs.debug }}
         run: |
           goreleaser release --clean --snapshot
 
-      - name: Save Docker Image to Tarball and Upload
+      - id: save-image-tarballs
+        name: Save Docker Image to Tarball and Upload
+        shell: bash
+        env:
+          JQ_FILTER: |-
+            map(
+                select(
+                    # filter tags that look like version numbers suffixed with the short-sha
+                    # of the current commit and the current architecture (e.x. amd64 or arm64)
+                    (.Tag | test("^v?[0-9][.].+-\(env.SHORT_SHA)[^-]*-${{ matrix.arch }}"; "i"))
+
+                    # filter for images from the 'ghcr.io/emissary-ingress' repository that
+                    # also match one of the components goreleaser was configured to build for
+                    and (.Repository | test("^ghcr.io/emissary-ingress/(\(env.COMPONENTS))"; "i"))
+                )
+
+                # format the standard 'repository:tag' specifier
+                # for each image that matched the filter critera
+                | "\(.Repository):\(.Tag)"
+
+            # print the filtered image tags as a tab-separated list (because the @sh function
+            # will wrap each value in single quotes, which is even less helpful for script use)
+            ) | @tsv
         run: |
+          set -euo pipefail
+
+          trap 'STATUS=${?}; echo >&2 "${0}: Error on line "${LINENO}": ${BASH_COMMAND}"; exit ${STATUS}' ERR
+
+          mkdir -p ${{ github.workspace }}/artifacts/images
+
           docker images
 
-          docker save \
-              ghcr.io/emissary-ingress/apiext:latest-${{ matrix.arch }} \
-              ghcr.io/emissary-ingress/emissary:latest-${{ matrix.arch }} \
-              ghcr.io/emissary-ingress/kat-client:latest-${{ matrix.arch }} \
-              ghcr.io/emissary-ingress/kat-server:latest-${{ matrix.arch }} \
-              ghcr.io/emissary-ingress/test-auth:latest-${{ matrix.arch }} \
-              ghcr.io/emissary-ingress/test-shadow:latest-${{ matrix.arch }} \
-              ghcr.io/emissary-ingress/test-stats:latest-${{ matrix.arch }} \
-            -o images-${{ matrix.arch }}.tar
+          SHORT_SHA="${GITHUB_SHA:0:8}"
+          COMPONENTS="$(echo '${{ inputs.components }}' | tr ' ' '|')"
 
-          echo "DOCKER_TARBALL_NAME=images-${{ matrix.arch }}.tar" >> $GITHUB_ENV
+          COMPONENT_IMAGES=($(docker images --no-trunc --format json | jq -sr "${JQ_FILTER}" | tr '\t' ' '))
 
-      - name: Set outputs
-        id: set-outputs
+          for IMAGE in ${COMPONENT_IMAGES[@]}; do
+              COMPONENT="$(echo "${IMAGE}" | tr ':' '/' | cut -d'/' -f3)"
+              IMAGE_PATH="${{ github.workspace }}/artifacts/images/${COMPONENT}-${{ matrix.arch }}-image.tar"
+
+              docker save "${IMAGE}" -o "${IMAGE_PATH}" \
+              || { EXIT_CODE=$?; echo "failed to save image tarball for: ${COMPONENT}" 1>&2; exit ${EXIT_CODE}; }
+
+              printf 'saved image tarball:\n\tcomponent: %s\n\tpath: %s\n\timage: %s\n' "${COMPONENT}" "${IMAGE_PATH}" "${IMAGE}"
+          done
+
+      - id: start-upterm-session
+        name: Start upterm session
+        shell: bash
+        continue-on-error: false
+        if: ${{ env.ACT == 'true' && (inputs.debug || steps.goreleaser-build.outcome == 'failure' || steps.save-image-tarballs.outcome == 'failure') }}
+        env:
+          CONTEXT: |
+            {
+              "env": ${{ toJSON(env) }},
+              "job": ${{ toJSON(job) }},
+              "vars": ${{ toJSON(vars) }},
+              "needs": ${{ toJSON(needs) }},
+              "steps": ${{ toJSON(steps) }},
+              "github": ${{ toJSON(github) }},
+              "inputs": ${{ toJSON(inputs) }},
+              "matrix": ${{ toJSON(matrix) }},
+              "runner": ${{ toJSON(runner) }},
+              "secrets": ${{ toJSON(secrets) }},
+              "strategy": ${{ toJSON(strategy) }}
+            }
         run: |
-          echo "artifact-name-prefix=images-${{ github.sha }}" >> $GITHUB_OUTPUT
+          export CONTEXT="$({ echo '---'; yq -Po yaml --null-input 'env(CONTEXT)'; })"
 
-      - name: Upload Docker Image Artifact
-        uses: actions/upload-artifact@v4
+          expect -c '
+          log_user 0
+          spawn upterm host --accept -- bash
+          expect {
+            -re "(yes/no)" { send "yes\r" }
+          }
+          log_user 1
+          interact
+          '
+
+          upterm session current
+
+          while pgrep upterm > /dev/null; do
+              sleep 5
+          done
+
+          if [[ "${{ steps.goreleaser-build.outcome == 'failure' || steps.save-image-tarballs.outcome == 'failure' }}" == 'true' ]]; then
+              exit 500
+          fi
+
+      - id: upload-image-tarballs
+        name: Upload Docker Image Artifact
+        uses: actions/upload-artifact@v5
         with:
-          name: images-${{ github.sha }}-${{ matrix.arch }}
-          path: ${{ env.DOCKER_TARBALL_NAME }}
+          name: ${{ inputs.artifact-bundle-prefix }}-${{ matrix.arch }}
           retention-days: 7
           if-no-files-found: error
+          path: ${{ github.workspace }}/artifacts/images/*.tar
diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -5,10 +5,49 @@ on:
   workflow_call:
     inputs:
       ref:
-        description: 'Git ref to checkout'
-        required: false
         type: string
+        required: false
         default: ${{ github.ref }}
+        description: Git ref to checkout
+      debug:
+        type: boolean
+        required: false
+        default: false
+        description: |
+          Enable upterm debugging
+
+          NOTE: only available when running locally with netkos/act
+      components:
+        type: string
+        required: true
+        description: >-
+          The list of components to build images for, formatted as a space-separated list of strings.
+      chart-registry:
+        type: string
+        required: false
+        default: ghcr.io/emissary-ingress
+        description: |
+          OCI repository to push charts to
+
+          Defaults to: ghcr.io/emissary-ingress
+      image-registry:
+        type: string
+        required: false
+        default: ghcr.io/emissary-ingress
+        description: |
+          OCI repository to push images to
+
+          Defaults to: ghcr.io/emissary-ingress
+
+    outputs:
+      pushed-charts:
+        value: ${{ jobs.release.outputs.pushed-charts }}
+        description: >-
+          TODO
+      pushed-images:
+        value: ${{ jobs.release.outputs.pushed-images }}
+        description: >-
+          TODO
 
 permissions:
   contents: read
@@ -17,16 +56,203 @@ jobs:
   release:
     name: Create GitHub Release
     runs-on: ubuntu-latest
+
+    outputs:
+      pushed-charts: ${{ steps.push-artifacts.outputs.pushed-charts }}
+      pushed-images: ${{ steps.push-artifacts.outputs.pushed-images }}
+
     steps:
-      - name: Would Release
-        run: echo "Would release here..."
-      # - name: Install Deps
-      #   uses: ./.github/actions/setup-deps
-      # - name: GoReleaser Build
-      #   shell: bash
-      #   run: |
-      #     echo 'insert gh cli magic here'
-      #     exit 412
-      # - name: Collect Job Logs
-      #   uses: ./.github/actions/after-job
-      #   if: always()
+      # 1) pull down image and chart tarballs from actions/upload-artifact@v5
+      # 2) unpack and organize tarballs into discrete image / chart bundles
+      # 3) push single-arch images to GHCR/DockerHub
+      # 4) create and push multi-arch manifest to GHCR/DockerHub
+      # 5) push individual chart (ingress & crds) artifacts to GHCR/DockerHub
+      # 6) cut an actual GitHub release
+      # 7) Party on Wayne
+      - name: Checkout
+        if: ${{ env.ACT }}
+        uses: actions/checkout@v5
+        with:
+          ref: ${{ inputs.ref }}
+          fetch-depth: 0
+
+      - name: Install Deps
+        if: ${{ env.ACT }}
+        uses: ./.github/actions/setup-deps
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Configure Docker GHCR Auth
+        shell: bash
+        run: |
+          echo ${{ github.token }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
+
+      - id: download-artifacts
+        name: Download CI Artifacts
+        uses: actions/download-artifact@v6
+        with:
+          merge-multiple: true
+          path: ${{ github.workspace }}/artifacts
+
+      - id: push-artifacts
+        name: Push Release Artifacts
+        shell: bash
+        continue-on-error: ${{ env.ACT && inputs.debug }}
+        env:
+          # possible values for `runner.arch`: ["X86", "X64", "ARM", "ARM64"]
+          # see https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#example
+          # for GitHub's explanation of using conditional logic in expressions
+          ARCHES: ${{ (env.ACT == 'true' && (runner.arch == 'X86' && 'AMD64' || runner.arch )) || 'AMD64 ARM64' }}
+        run: |
+          set -euo pipefail
+
+          trap 'STATUS=${?}; echo >&2 "${0}: Error on line "${LINENO}": ${BASH_COMMAND}"; exit ${STATUS}' ERR
+
+          # NOTE: intended meaning of exit codes match their HTTP status equivilent (e.g., exit code 404 == '(file) not found')
+
+          PUSHED_CHARTS=()
+          PUSHED_IMAGES=()
+          ARCHES=($(echo ${ARCHES} | tr '[[:upper:]]' '[[:lower:]]'))
+
+          echo -e "pushing images for:\n\tarches: ${ARCHES[@]}\n\tcomponents: ${{ inputs.components }}"
+
+          for COMPONENT in ${{ inputs.components }}; do
+              COMPONENT_IMAGES=()
+
+              for ARCH in ${ARCHES[@]}; do
+                  IMAGE_PATH="${{ github.workspace }}/artifacts/${COMPONENT}-${ARCH}-image.tar"
+
+                  if [[ ! -f "${IMAGE_PATH}" ]]; then
+                      echo "Tarball for ${COMPONENT}/${ARCH} not found at expected path: ${IMAGE_PATH}" 1>&2
+                      exit 404  # (file) not found
+                  fi
+
+                  LOADED_IMAGE="$(docker load --input "${IMAGE_PATH}" | cut -d' ' -f3)" \
+                  || { EXIT_CODE=$?; echo "failed to load image from tarball: ${IMAGE_PATH}" 1>&2; exit ${EXIT_CODE}; }
+
+                  LOADED_TAG="$(echo "${LOADED_IMAGE}" | cut -d':' -f2)"
+
+                  if ! echo "${LOADED_TAG}" | grep -E -- "-${ARCH}$" > /dev/null 2>&1; then
+                      LOADED_TAG+="-${ARCH}"
+                  fi
+
+                  COMPONENT_ARCH_TAG="${{ inputs.image-registry }}/${COMPONENT}:${LOADED_TAG}"
+
+                  echo "loaded image: ${LOADED_IMAGE}"
+
+                  docker tag "${LOADED_IMAGE}" "${COMPONENT_ARCH_TAG}" \
+                  || { EXIT_CODE=$?; echo "failed to tag loaded image: [loaded: ${LOADED_IMAGE}, tag: ${COMPONENT_ARCH_TAG}]" 1>&2; exit ${EXIT_CODE}; }
+
+                  docker push "${COMPONENT_ARCH_TAG}" \
+                  || { EXIT_CODE=$?; echo "failed to push tagged component image: ${COMPONENT_ARCH_TAG}" 1>&2; exit ${EXIT_CODE}; }
+
+                  PUSHED_IMAGES+=("${COMPONENT_ARCH_TAG}")
+                  COMPONENT_IMAGES+=("--amend" "${COMPONENT_ARCH_TAG}")
+              done
+
+              MANIFEST_TAG="$(echo "${COMPONENT_IMAGES[1]}" | sed -E 's#-(arm|amd)64$##Ig')"
+
+              echo "creating multi-arch manifest for: ${MANIFEST_TAG}"
+
+              docker manifest create "${MANIFEST_TAG}" ${COMPONENT_IMAGES[@]} \
+              || { EXIT_CODE=$?; echo "failed to create multi-arch manifest: ${MANIFEST_TAG}" 1>&2; exit ${EXIT_CODE}; }
+
+              MANIFEST_SHA="$(docker manifest push "${MANIFEST_TAG}")" \
+              || { EXIT_CODE=$?; echo "failed to push multi-arch manifest: ${MANIFEST_TAG}" 1>&2; exit ${EXIT_CODE}; }
+
+              echo "pushed multi-arch manifest: ${MANIFEST_TAG} (digest: ${MANIFEST_SHA})"
+
+              PUSHED_IMAGES+=("${MANIFEST_TAG}")
+          done
+
+          echo "pushed-images=${PUSHED_IMAGES[@]}" >> "${GITHUB_OUTPUT}"
+
+          CHART_TARBALLS=($(echo ${{ github.workspace }}/artifacts/emissary-{crds,ingress}-*.tgz))
+
+          if [[ "${#CHART_TARBALLS[@]}" -eq 0 ]]; then
+              echo "expected exactly 2 chart tarballs, but found none" 1>&2
+              exit 412  # precondition failed
+          elif [[ "${#CHART_TARBALLS[@]}" -eq 1 ]]; then
+              echo "expected exactly 2 chart tarballs, but only found one: ${CHART_TARBALLS}" 1>&2
+              exit 412  # precondition failed
+          elif [[ "${#CHART_TARBALLS[@]}" -gt 2 ]]; then
+              echo -e \
+              "WARNING: expected exactly 2 chart tarballs, but found ${#CHART_TARBALLS[@]}:\n" \
+              "$(IFS=$'\n'; echo "${CHART_TARBALLS[*]}" | sed -E 's#^#\t#')"
+              echo "WARNING: proceeding with chart pushes, but it'd probably be a " \
+              "good idea for an emissary maintainer to double-check the pushed charts"
+          fi
+
+          for CHART in ${CHART_TARBALLS[@]}; do
+              echo "pushing chart: ${CHART}"
+
+              PUSH_RESULT="$(helm push "${CHART}" oci://${{ inputs.chart-registry }} \
+              --username ${{ github.actor }} --password ${{ github.token }} 2>&1)" \
+              || { EXIT_CODE=$?; echo "failed to push helm chart tarball: ${CHART}" 1>&2; exit ${EXIT_CODE}; }
+
+              PUSHED_CHART="$(printf '%s\n' "${PUSH_RESULT}" | head -n1 | cut -d' ' -f2)"
+              PUSHED_DIGEST="$(printf '%s\n' "${PUSH_RESULT}" | tail -n1 | cut -d' ' -f2)"
+
+              printf 'pushed chart: %s (digest: %s)\n' "${PUSHED_CHART}" "${PUSHED_DIGEST}"
+
+              PUSHED_CHARTS+=("${PUSHED_CHART}")
+          done
+
+          echo "pushed-charts=${PUSHED_CHARTS[@]}" >> "${GITHUB_OUTPUT}"
+
+      - id: start-upterm-session
+        name: Start upterm session
+        shell: bash
+        if: ${{ env.ACT == 'true' && (inputs.debug || steps.push-artifacts.outcome == 'failure') }}
+        env:
+          CONTEXT: |
+            {
+              "env": ${{ toJSON(env) }},
+              "job": ${{ toJSON(job) }},
+              "vars": ${{ toJSON(vars) }},
+              "needs": ${{ toJSON(needs) }},
+              "steps": ${{ toJSON(steps) }},
+              "github": ${{ toJSON(github) }},
+              "inputs": ${{ toJSON(inputs) }},
+              "matrix": ${{ toJSON(matrix) }},
+              "runner": ${{ toJSON(runner) }},
+              "secrets": ${{ toJSON(secrets) }},
+              "strategy": ${{ toJSON(strategy) }}
+            }
+        run: |
+          export CONTEXT="$({ echo '---'; yq -Po yaml --null-input 'env(CONTEXT)'; })"
+
+          expect -c '
+          log_user 0
+          spawn upterm host --accept -- bash
+          expect {
+            -re "(yes/no)" { send "yes\r" }
+          }
+          log_user 1
+          interact
+          '
+
+          upterm session current
+
+          while pgrep upterm > /dev/null; do
+              sleep 5
+          done
+
+          if [[ "${{ steps.push-artifacts.outcome == 'failure' }}" == 'true' ]]; then
+              exit 500
+          fi
+
+#      - id: release-artifacts
+#        name: Release
+#        uses: softprops/action-gh-release@v2
+#        with:
+#          make_latest: true
+#          fail_on_unmatched_files: true
+#          tag_name: ${{ inputs.release-tag || github.ref_name }}
+#          files: |
+#            ${{ github.workspace }}/artifacts/*
+#
+#      - name: Collect Job Logs
+#        uses: ./.github/actions/after-job
+#        if: always()
